In [1]:
import pandas as pd
import pandas_datareader.data as web
import datetime
from Indicator import Indicator

def fillindicator(df):
    indicator = Indicator()
    train_set = indicator.MA(df,15)
    train_set = indicator.MACD(df)
    train_set = indicator.STOCHASTIC(df)
    train_set = indicator.RSI(df)
    train_set = indicator.WILLIAMSR(df)
    return train_set

In [2]:
stockname = pd.read_csv('stock.csv')

In [16]:
def check_trend(df):
    df.loc[(df['Close'] > df['MA']) &
    ((df['Close'] > df['Close'].shift(1)) | (df['MA'] > df['MA'].shift(1))) &
    ((df['Close'] > df['Close'].shift(2)) | (df['MA'] > df['MA'].shift(2))) &
    ((df['Close'] > df['Close'].shift(3)) | (df['MA'] > df['MA'].shift(3))) &
    ((df['Close'] > df['Close'].shift(4)) | (df['MA'] > df['MA'].shift(4))) &
    ((df['Close'] > df['Close'].shift(5)) | (df['MA'] > df['MA'].shift(5))) , 'Trend'] = 'Up'

    df.loc[(df['Close'] < df['MA']) &
    ((df['Close'] < df['Close'].shift(1)) | (df['MA'] < df['MA'].shift(1))) &
    ((df['Close'] < df['Close'].shift(2)) | (df['MA'] < df['MA'].shift(2))) &
    ((df['Close'] < df['Close'].shift(3)) | (df['MA'] < df['MA'].shift(3))) &
    ((df['Close'] < df['Close'].shift(4)) | (df['MA'] < df['MA'].shift(4))) &
    ((df['Close'] < df['Close'].shift(5)) | (df['MA'] < df['MA'].shift(5))) , 'Trend'] = 'Down'
    
    df.loc[df['Trend'].isnull(), 'Ntrend'] = df['Trend'].shift(1)
    df.loc[df['Trend'].isnull() & df['Trend'].shift(1).isnull(),'Ntrend'] = df['Trend'].shift(2)
    df.loc[df['Trend'].isnull() & df['Trend'].shift(1).isnull() & df['Trend'].shift(2).isnull(),'Ntrend'] = df['Trend'].shift(3)
    df.loc[df['Trend'].isnull() & df['Trend'].shift(1).isnull() & df['Trend'].shift(2).isnull() & 
    df['Trend'].shift(3).isnull(),'Ntrend'] = df['Trend'].shift(4)
    df.loc[df['Trend'].isnull() & df['Trend'].shift(1).isnull() & df['Trend'].shift(2).isnull() & 
    df['Trend'].shift(3).isnull() & df['Trend'].shift(4).isnull(),'Ntrend'] = df['Trend'].shift(5)
    df.loc[df['Trend'].isnull() & df['Trend'].shift(1).isnull() & df['Trend'].shift(2).isnull() & 
    df['Trend'].shift(3).isnull() & df['Trend'].shift(4).isnull() & df['Trend'].shift(5).isnull(),'Ntrend'] = df['Trend'].shift(6)
    
    df.loc[df['Trend'].isnull(),'Trend'] = 'No'
    return df

In [3]:
start = datetime.datetime(2004,10,1)#26 day before start year for make indicator
end = datetime.datetime(2010,1,3)
# for i,row in stockname.iterrows():
#     df = web.DataReader(stockname['stock'][0],'yahoo',start,end)

In [14]:

df = web.DataReader(stockname['stock'][0],'yahoo',start,end)
df = fillindicator(df)
df = check_trend(df)

In [15]:
df

,High,Low,Open,Close,Volume,Adj Close,MA,MACD,SIGNAL LINE,%K,%D,RSI-7,RSI-14,%R,Trend
Date,,,,,,,,,,,,,,,
2004-12-13,79.449997,78.129997,79.050003,78.480003,3889700.0,51.305103,NaN,0.000000,0.000000,NaN,NaN,NaN,NaN,NaN,no
2004-12-14,79.199997,78.449997,78.500000,78.500000,3409800.0,51.318153,NaN,0.000449,0.000249,NaN,NaN,NaN,NaN,NaN,no
2004-12-15,79.440002,78.699997,78.870003,79.089996,4183900.0,51.703880,NaN,0.018867,0.007880,NaN,NaN,NaN,NaN,NaN,no
2004-12-16,80.599998,79.000000,79.139999,79.900002,4854100.0,52.233383,NaN,0.056027,0.024190,NaN,NaN,NaN,NaN,NaN,no
2004-12-17,80.900002,80.040001,80.400002,80.620003,6293200.0,52.704102,NaN,0.103690,0.047839,NaN,NaN,NaN,NaN,NaN,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2009-12-24,83.000000,82.309998,82.309998,82.550003,931200.0,61.443562,80.755334,1.344230,1.224383,93.304931,88.793986,68.810973,64.583145,-6.695069,Up
2009-12-28,83.589996,82.669998,82.779999,83.449997,2353800.0,62.113430,81.102667,1.425010,1.264508,98.155475,93.212374,74.642829,67.633054,-1.844525,Up
2009-12-29,84.320000,83.650002,83.779999,84.129997,3865900.0,62.619572,81.517333,1.526305,1.316868,96.969656,96.143354,78.230905,69.752491,-3.030344,Up
2009-12-30,84.300003,83.660004,84.000000,83.900002,2595000.0,62.448399,81.970000,1.569926,1.367479,90.869602,95.331578,74.093767,68.127552,-9.130398,Up
2009-12-31,84.080002,82.540001,83.790001,82.669998,2049800.0,61.532875,82.165334,1.488091,1.391602,58.542710,82.127323,55.711477,60.068314,-41.457290,Up